import json
from urllib import parse
import requests

urls = [
'https://tb.cn/V6NP18x',
'https://tb.cn/YrgO18x',
'https://tb.cn/jWNO18x',
]
cookies = [
{
    "domain": ".taobao.com",
    "expirationDate": 1518588423.550825,
    "hostOnly": False,
    "httpOnly": False,
    "name": "_cc_",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "V32FPkk%2Fhw%3D%3D",
    "id": 1
},
{
    "domain": ".taobao.com",
    "hostOnly": False,
    "httpOnly": False,
    "name": "_l_g_",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": True,
    "storeId": "0",
    "value": "Ug%3D%3D",
    "id": 2
},
{
    "domain": ".taobao.com",
    "hostOnly": False,
    "httpOnly": False,
    "name": "_nk_",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": True,
    "storeId": "0",
    "value": "%5Cu667A%5Cu53CB%5Cu8BBE%5Cu8BA1",
    "id": 3
},
{
    "domain": ".taobao.com",
    "hostOnly": False,
    "httpOnly": False,
    "name": "_tb_token_",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": True,
    "storeId": "0",
    "value": "5b9e5e64f3175",
    "id": 4
},
{
    "domain": ".taobao.com",
    "expirationDate": 1802336420.521421,
    "hostOnly": False,
    "httpOnly": False,
    "name": "ali_ab",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "219.136.144.169.1457063587521.2",
    "id": 5
},
{
    "domain": ".taobao.com",
    "expirationDate": 1800092206,
    "hostOnly": False,
    "httpOnly": False,
    "name": "cna",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "IuVeD/3vzBcCAduIkkCnXdb+",
    "id": 6
},
{
    "domain": ".taobao.com",
    "hostOnly": False,
    "httpOnly": True,
    "name": "cookie1",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": True,
    "storeId": "0",
    "value": "BxSjS%2F%2BSvCNjZ%2BHUfanhClBNR8j0Cp9uILmp5VV7hhM%3D",
    "id": 7
},
{
    "domain": ".taobao.com",
    "hostOnly": False,
    "httpOnly": True,
    "name": "cookie17",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": True,
    "storeId": "0",
    "value": "UUwQkA1lNFYXbQ%3D%3D",
    "id": 8
},
{
    "domain": ".taobao.com",
    "hostOnly": False,
    "httpOnly": True,
    "name": "cookie2",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": True,
    "storeId": "0",
    "value": "1d64b881f31039b72689c4e9ee583d35",
    "id": 9
},
{
    "domain": ".taobao.com",
    "hostOnly": False,
    "httpOnly": False,
    "name": "existShop",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": True,
    "storeId": "0",
    "value": "MTQ4NzA1MjQyMw%3D%3D",
    "id": 10
},
{
    "domain": ".taobao.com",
    "expirationDate": 1515566745.102436,
    "hostOnly": False,
    "httpOnly": False,
    "name": "hng",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "CN%7Czh-cn%7CCNY",
    "id": 11
},
{
    "domain": ".taobao.com",
    "expirationDate": 1502606691,
    "hostOnly": False,
    "httpOnly": False,
    "name": "isg",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "AiAgn3wEbMHxntDi1WJrkBk68Sj8EATz_9JKBZox7DvOlcC_QjnUg_anQ4rv",
    "id": 12
},
{
    "domain": ".taobao.com",
    "expirationDate": 1896134400,
    "hostOnly": False,
    "httpOnly": False,
    "name": "l",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "Aqmphe/Aj5oHTeizqbxN4pihOV8Ddp2o",
    "id": 13
},
{
    "domain": ".taobao.com",
    "expirationDate": 1489644423.550005,
    "hostOnly": False,
    "httpOnly": False,
    "name": "lgc",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "%5Cu667A%5Cu53CB%5Cu8BBE%5Cu8BA1",
    "id": 14
},
{
    "domain": ".taobao.com",
    "expirationDate": 1788578914,
    "hostOnly": False,
    "httpOnly": False,
    "name": "lzstat_uv",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "18677630473752898585|2144678",
    "id": 15
},
{
    "domain": ".taobao.com",
    "expirationDate": 1547604613.128304,
    "hostOnly": False,
    "httpOnly": False,
    "name": "miid",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "8179496107237979619",
    "id": 16
},
{
    "domain": ".taobao.com",
    "expirationDate": 1487657223.550509,
    "hostOnly": False,
    "httpOnly": False,
    "name": "mt",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "np=&ci=57_1",
    "id": 17
},
{
    "domain": ".taobao.com",
    "hostOnly": False,
    "httpOnly": False,
    "name": "sg",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": True,
    "storeId": "0",
    "value": "%E8%AE%A185",
    "id": 18
},
{
    "domain": ".taobao.com",
    "hostOnly": False,
    "httpOnly": True,
    "name": "skt",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": True,
    "storeId": "0",
    "value": "488f28ed234c58fe",
    "id": 19
},
{
    "domain": ".taobao.com",
    "expirationDate": 1494828423.550722,
    "hostOnly": False,
    "httpOnly": False,
    "name": "t",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "7118535fd794053ff6ccbb629c903ef9",
    "id": 20
},
{
    "domain": ".taobao.com",
    "expirationDate": 1541052423.550941,
    "hostOnly": False,
    "httpOnly": False,
    "name": "tg",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "0",
    "id": 21
},
{
    "domain": ".taobao.com",
    "expirationDate": 1488591934.357312,
    "hostOnly": False,
    "httpOnly": False,
    "name": "thw",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "cn",
    "id": 22
},
{
    "domain": ".taobao.com",
    "expirationDate": 1518588423.550343,
    "hostOnly": False,
    "httpOnly": False,
    "name": "tracknick",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "%5Cu667A%5Cu53CB%5Cu8BBE%5Cu8BA1",
    "id": 23
},
{
    "domain": ".taobao.com",
    "hostOnly": False,
    "httpOnly": False,
    "name": "uc1",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": True,
    "storeId": "0",
    "value": "cookie14=UoW%2FWvFLBBt7ug%3D%3D&lng=zh_CN&cookie16=UtASsssmPlP%2Ff1IHDsDaPRu%2BPw%3D%3D&existShop=True&cookie21=UtASsssmfaCONGki4KTH3w%3D%3D&tag=0&cookie15=WqG3DMC9VAQiUQ%3D%3D&pas=0",
    "id": 24
},
{
    "domain": ".taobao.com",
    "expirationDate": 1489644423.549147,
    "hostOnly": False,
    "httpOnly": True,
    "name": "uc3",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "sg2=BYjZvYYDr4DdEKP27wcbgDU8xyLkx0uDfmYgbI3kLDo%3D&nk2=tYzvT6WaNFM%3D&id2=UUwQkA1lNFYXbQ%3D%3D&vt3=F8dARHtOjq%2BjRhXytSw%3D&lg2=Vq8l%2BKCLz3%2F65A%3D%3D",
    "id": 25
},
{
    "domain": ".taobao.com",
    "hostOnly": False,
    "httpOnly": True,
    "name": "unb",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": True,
    "storeId": "0",
    "value": "2406822118",
    "id": 26
},
{
    "domain": ".taobao.com",
    "expirationDate": 1489644423.549736,
    "hostOnly": False,
    "httpOnly": True,
    "name": "uss",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "AV13CeoEF1KkWPLMdPlkMo%2FI3RA%2Fa5Rc58mz4NEDqwsmnCOp3wQXXeaVZA%3D%3D",
    "id": 27
},
{
    "domain": ".taobao.com",
    "hostOnly": False,
    "httpOnly": False,
    "name": "v",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": True,
    "storeId": "0",
    "value": "0",
    "id": 28
},
{
    "domain": ".taobao.com",
    "expirationDate": 1512213739,
    "hostOnly": False,
    "httpOnly": False,
    "name": "x",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "e%3D1%26p%3D*%26s%3D0%26c%3D0%26f%3D0%26g%3D0%26t%3D0%26__ll%3D-1%26_ato%3D0",
    "id": 29
},
{
    "domain": "wuxian.taobao.com",
    "hostOnly": True,
    "httpOnly": False,
    "name": "apush972f82663d2cac37c8e657a3ebeddb82",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": True,
    "storeId": "0",
    "value": "%7B%22ts%22%3A1487054691665%2C%22parentId%22%3A1487054690652%7D",
    "id": 30
},
{
    "domain": "wuxian.taobao.com",
    "expirationDate": 1502763417,
    "hostOnly": True,
    "httpOnly": False,
    "name": "CNZZDATA30085636",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "cnzz_eid%3D1102923280-1487036379-http%253A%252F%252Fwuxian.taobao.com%252F%26ntime%3D1487036379",
    "id": 31
},
{
    "domain": "wuxian.taobao.com",
    "expirationDate": 1488272393,
    "hostOnly": True,
    "httpOnly": False,
    "name": "miniDialog",
    "path": "/spark",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "True",
    "id": 32
},
{
    "domain": "wuxian.taobao.com",
    "expirationDate": 1489568298,
    "hostOnly": True,
    "httpOnly": False,
    "name": "ws_notice",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "%5Cu667A%5Cu53CB%5Cu8BBE%5Cu8BA1566",
    "id": 33
}
]
headers = {
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36'
}

newCookies = {}
for item in cookies:
    newCookies[item['name']] = item['value']

results = []
for url in urls:
    r = requests.get(url, headers=headers, cookies=newCookies)
    results.append({
        'url': url.replace('https://', '//'),
        'qnUrl': parse.unquote(r.url.replace('https://', '//qianniu.'))
    })

print(json.dumps(results, indent=2, ensure_ascii=False))
